@{
    RootModule           = 'ServiceM8.psm1'
    ModuleVersion        = '0.1.0'
    GUID                 = 'b6f4a2e1-3c7d-4f8a-9b2e-1a5c6d7e8f90'
    Author               = 'Caspa IT'
    CompanyName          = 'Caspa'
    Copyright            = '(c) Caspa. All rights reserved.'
    Description          = 'PowerShell wrapper for the ServiceM8 REST API: OAuth authentication and typed resource cmdlets.'

    PowerShellVersion    = '7.0'

    FunctionsToExport    = @(
        'Import-Sm8Config',
        'Connect-Sm8Client',
        'Get-Sm8Token',
        'Invoke-Sm8Request',
        'Invoke-Sm8List',
        'Invoke-Sm8Resource',
        'Get-Sm8ResourceRoot',
        'Get-Sm8Registry',
        'Get-Sm8AllocationWindow',
        'New-Sm8AllocationWindow',
        'Update-Sm8AllocationWindow',
        'Remove-Sm8AllocationWindow',
        'Get-Sm8Asset',
        'New-Sm8Asset',
        'Update-Sm8Asset',
        'Remove-Sm8Asset',
        'Get-Sm8AssetType',
        'New-Sm8AssetType',
        'Update-Sm8AssetType',
        'Remove-Sm8AssetType',
        'Get-Sm8AssetTypeField',
        'New-Sm8AssetTypeField',
        'Update-Sm8AssetTypeField',
        'Remove-Sm8AssetTypeField',
        'Get-Sm8Attachment',
        'New-Sm8Attachment',
        'Update-Sm8Attachment',
        'Remove-Sm8Attachment',
        'Get-Sm8Availability',
        'New-Sm8Availability',
        'Update-Sm8Availability',
        'Remove-Sm8Availability',
        'Get-Sm8Badge',
        'Get-Sm8Bundle',
        'New-Sm8Bundle',
        'Update-Sm8Bundle',
        'Remove-Sm8Bundle',
        'Get-Sm8Category',
        'New-Sm8Category',
        'Update-Sm8Category',
        'Remove-Sm8Category',
        'Get-Sm8Client',
        'New-Sm8Client',
        'Update-Sm8Client',
        'Remove-Sm8Client',
        'Get-Sm8Company',
        'New-Sm8Company',
        'Update-Sm8Company',
        'Remove-Sm8Company',
        'Get-Sm8CompanyContact',
        'New-Sm8CompanyContact',
        'Update-Sm8CompanyContact',
        'Remove-Sm8CompanyContact',
        'Get-Sm8DocumentTemplate',
        'Get-Sm8EmailTemplate',
        'Get-Sm8Feedback',
        'New-Sm8Feedback',
        'Update-Sm8Feedback',
        'Remove-Sm8Feedback',
        'Get-Sm8Form',
        'New-Sm8Form',
        'Update-Sm8Form',
        'Remove-Sm8Form',
        'Get-Sm8FormField',
        'New-Sm8FormField',
        'Update-Sm8FormField',
        'Remove-Sm8FormField',
        'Get-Sm8FormResponse',
        'New-Sm8FormResponse',
        'Update-Sm8FormResponse',
        'Remove-Sm8FormResponse',
        'Get-Sm8Job',
        'New-Sm8Job',
        'Update-Sm8Job',
        'Remove-Sm8Job',
        'Get-Sm8JobActivity',
        'New-Sm8JobActivity',
        'Update-Sm8JobActivity',
        'Remove-Sm8JobActivity',
        'Get-Sm8JobAllocation',
        'New-Sm8JobAllocation',
        'Update-Sm8JobAllocation',
        'Remove-Sm8JobAllocation',
        'Get-Sm8JobChecklist',
        'New-Sm8JobChecklist',
        'Update-Sm8JobChecklist',
        'Remove-Sm8JobChecklist',
        'Get-Sm8JobContact',
        'New-Sm8JobContact',
        'Update-Sm8JobContact',
        'Remove-Sm8JobContact',
        'Get-Sm8JobMaterial',
        'New-Sm8JobMaterial',
        'Update-Sm8JobMaterial',
        'Remove-Sm8JobMaterial',
        'Get-Sm8JobPayment',
        'New-Sm8JobPayment',
        'Update-Sm8JobPayment',
        'Remove-Sm8JobPayment',
        'Get-Sm8JobQueue',
        'New-Sm8JobQueue',
        'Update-Sm8JobQueue',
        'Remove-Sm8JobQueue',
        'Get-Sm8JobTemplate',
        'New-Sm8JobTemplate',
        'Update-Sm8JobTemplate',
        'Remove-Sm8JobTemplate',
        'Get-Sm8KnowledgeArticle',
        'New-Sm8KnowledgeArticle',
        'Update-Sm8KnowledgeArticle',
        'Remove-Sm8KnowledgeArticle',
        'Get-Sm8Location',
        'New-Sm8Location',
        'Update-Sm8Location',
        'Remove-Sm8Location',
        'Get-Sm8Material',
        'New-Sm8Material',
        'Update-Sm8Material',
        'Remove-Sm8Material',
        'Get-Sm8Note',
        'New-Sm8Note',
        'Update-Sm8Note',
        'Remove-Sm8Note',
        'Get-Sm8SecurityRole',
        'Get-Sm8Smstemplate',
        'Get-Sm8StaffMember',
        'New-Sm8StaffMember',
        'Update-Sm8StaffMember',
        'Remove-Sm8StaffMember',
        'Get-Sm8StaffMessage',
        'New-Sm8StaffMessage',
        'Update-Sm8StaffMessage',
        'Remove-Sm8StaffMessage',
        'Get-Sm8Supplier',
        'New-Sm8Supplier',
        'Update-Sm8Supplier',
        'Remove-Sm8Supplier',
        'Get-Sm8Task',
        'New-Sm8Task',
        'Update-Sm8Task',
        'Remove-Sm8Task',
        'Get-Sm8TaxRate',
        'New-Sm8TaxRate',
        'Update-Sm8TaxRate',
        'Remove-Sm8TaxRate'
    )
    CmdletsToExport     = @()
    VariablesToExport   = @()
    AliasesToExport     = @()

    PrivateData          = @{
        PSData = @{
            Tags         = @('ServiceM8', 'API', 'OAuth', 'REST', 'FieldService')
            ProjectUri   = 'https://github.com/CaspaIT/ServiceM8'
            LicenseUri   = 'https://github.com/CaspaIT/ServiceM8/blob/main/LICENSE'
        }
    }
}






