<#
.SYNOPSIS
    Regenerate the typed cmdlets module (src/ServiceM8.Cmdlets.psm1) from the
    resource registry (src/ServiceM8.Registry.psm1).

.DESCRIPTION
    The registry is the single source of truth. Running this script writes
    one set of typed cmdlets (Get/New/Update/Remove) per resource, so adding a
    resource is: edit the registry, run the generator, commit.

    Generated cmdlets delegate to Invoke-Sm8Resource (the single portable CRUD
    entry point in the engine), so the API path lives in exactly one place.

.PARAMETER OutputPath
    Where to write the generated module. Defaults to src/ServiceM8.Cmdlets.psm1.

.EXAMPLE
    .\scripts\Generate-Module.ps1
#>

[CmdletBinding()]
param(
    [string] $OutputPath = (Join-Path $PSScriptRoot '..' 'src' 'ServiceM8.Cmdlets.psm1')
)

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Load the registry (raw function definition, so Get-Sm8Registry is in scope).
# Strip the leading <# ... #> doc comment and the Export-ModuleMember line so
# Invoke-Expression loads just the function into this script's scope.
# ---------------------------------------------------------------------------
$regModule = Join-Path $PSScriptRoot '..' 'src' 'ServiceM8.Registry.psm1'
$regContent = Get-Content -LiteralPath $regModule -Raw
$regContent = [regex]::Replace($regContent, '(?s)^<#.*?#>', '')
$regContent = $regContent -replace '(?m)^\s*Export-ModuleMember.*$', ''
Invoke-Expression $regContent
$registry = @(Get-Sm8Registry)

# ---------------------------------------------------------------------------
# Build the generated module.
# NOTE: use single-quoted strings for any line that must contain a literal $
# (PowerShell's only string interpolation is double quotes; backslash is NOT
# an escape char). Interpolate $name by concatenation.
# ---------------------------------------------------------------------------
$lines = New-Object System.Collections.Generic.List[string]

$lines.Add('<#')
$lines.Add('    ServiceM8.Cmdlets')
$lines.Add('    Typed cmdlets over the ServiceM8 engine.')
$lines.Add('')
$lines.Add('    AUTO-GENERATED by scripts/Generate-Module.ps1 from the resource registry.')
$lines.Add('    Do not edit by hand -- update the registry and regenerate.')
$lines.Add('    Each cmdlet delegates to Invoke-Sm8Resource (the single portable CRUD entry point).')
$lines.Add('#>')
$lines.Add('')
$lines.Add('Set-StrictMode -Version Latest')
$lines.Add('')

foreach ($r in $registry | Sort-Object Name) {
    $name = $r.Name

    $emitGet = [bool]$r.ReadScope
    $emitNew = [bool]$r.WriteScope -and $r.WriteScope -ne $r.ReadScope
    $emitUpdate = [bool]$r.DeleteScope -and $r.DeleteScope -ne $r.ReadScope
    $emitDelete = [bool]$r.DeleteScope -and $r.DeleteScope -ne $r.ReadScope

    $scopeNote = @()
    if ($r.ReadScope)  { $scopeNote += "read: $($r.ReadScope)" }
    if ($r.WriteScope) { $scopeNote += "create: $($r.WriteScope)" }
    if ($r.DeleteScope) { $scopeNote += "delete/update: $($r.DeleteScope)" }
    $scopeLine = "    # scopes -> " + ($scopeNote -join ', ')

    # ---- Get ----
    if ($emitGet) {
        $desc = "List or retrieve $name records."
        $lines.Add("")
        $lines.Add("# ---------------------------------------------------------------------------")
        $lines.Add("# " + $name)
        $lines.Add("# ---------------------------------------------------------------------------")
        $lines.Add("")
        $lines.Add("function Get-Sm8" + $name + " {")
        $lines.Add("    <#")
        $lines.Add("    .SYNOPSIS")
        $lines.Add("        " + $desc)
        $lines.Add("    .DESCRIPTION")
        $lines.Add("        Retrieve a single record by -Uuid, or list records. With -All")
        $lines.Add("        every record is returned (pagination is followed automatically);")
        $lines.Add("        without it the first page is returned.")
        $lines.Add("    .EXAMPLE")
        $lines.Add("        Get-Sm8" + $name + " -All")
        $lines.Add("    .EXAMPLE")
        $lines.Add("        Get-Sm8" + $name + " -Uuid '123e4567-c6e7-7d94-8a1f-2c225b01e65b'")
        $lines.Add("    #>")
        $lines.Add("    [CmdletBinding(SupportsShouldProcess)]")
        $lines.Add("    [OutputType([pscustomobject[]])]")
        $lines.Add("    param(")
        $lines.Add('        [string] $Uuid,')
        $lines.Add('        [switch] $All,')
        $lines.Add('        [hashtable] $Query')
        $lines.Add("    )")
        $lines.Add("")
        $lines.Add('    return Invoke-Sm8Resource -Resource "' + $name + '" -Verb Get -Uuid $Uuid -All:$All -Query $Query')
        $lines.Add("}")
        $lines.Add("")
    }

    # ---- New ----
    if ($emitNew) {
        $lines.Add("function New-Sm8" + $name + " {")
        $lines.Add("    <#")
        $lines.Add("    .SYNOPSIS")
        $lines.Add("        Create a new $name.")
        $lines.Add("    .EXAMPLE")
        $lines.Add("        New-Sm8" + $name + " -Body @{ date = '2026-09-09' }")
        $lines.Add("    #>")
        $lines.Add("    [CmdletBinding(SupportsShouldProcess)]")
        $lines.Add("    [OutputType([pscustomobject])]")
        $lines.Add("    param(")
        $lines.Add('        [Parameter(Mandatory)] [object] $Body')
        $lines.Add("    )")
        $lines.Add("")
        $lines.Add('    return Invoke-Sm8Resource -Resource "' + $name + '" -Verb Post -Body $Body')
        $lines.Add("}")
        $lines.Add("")
    }

    # ---- Update ----
    if ($emitUpdate) {
        $lines.Add("function Update-Sm8" + $name + " {")
        $lines.Add("    <#")
        $lines.Add("    .SYNOPSIS")
        $lines.Add("        Update an existing $name.")
        $lines.Add("    .EXAMPLE")
        $lines.Add("        Update-Sm8" + $name + " -Uuid '123e4567-...' -Body @{ date = '2026-09-10' }")
        $lines.Add("    #>")
        $lines.Add("    [CmdletBinding(SupportsShouldProcess)]")
        $lines.Add("    [OutputType([pscustomobject])]")
        $lines.Add("    param(")
        $lines.Add('        [Parameter(Mandatory)] [string] $Uuid,')
        $lines.Add('        [Parameter(Mandatory)] [object] $Body')
        $lines.Add("    )")
        $lines.Add("")
        $lines.Add('    return Invoke-Sm8Resource -Resource "' + $name + '" -Verb Update -Uuid $Uuid -Body $Body')
        $lines.Add("}")
        $lines.Add("")
    }

    # ---- Remove ----
    if ($emitDelete) {
        $lines.Add("function Remove-Sm8" + $name + " {")
        $lines.Add("    <#")
        $lines.Add("    .SYNOPSIS")
        $lines.Add("        Delete (deactivate) a $name record (sets active=0).")
        $lines.Add("    #>")
        $lines.Add("    [CmdletBinding(SupportsShouldProcess, ConfirmImpact='Medium')]")
        $lines.Add("    param(")
        $lines.Add('        [Parameter(Mandatory, ValueFromPipeline)] [string] $Uuid')
        $lines.Add("    )")
        $lines.Add("    process {")
        $lines.Add('        return Invoke-Sm8Resource -Resource "' + $name + '" -Verb Delete -Uuid $Uuid')
        $lines.Add("    }")
        $lines.Add("}")
        $lines.Add("")
    }

    $lines.Add($scopeLine)
    $lines.Add("")
}

# ---- Export ----
$exported = @()
foreach ($r in $registry | Sort-Object Name) {
    $name = $r.Name
    if ($r.ReadScope) { $exported += "Get-Sm8$name" }
    if ($r.WriteScope -and $r.WriteScope -ne $r.ReadScope) { $exported += "New-Sm8$name" }
    if ($r.DeleteScope -and $r.DeleteScope -ne $r.ReadScope) { $exported += "Update-Sm8$name", "Remove-Sm8$name" }
}

$lines.Add("Export-ModuleMember -Function " + ($exported -join ", "))

# ---------------------------------------------------------------------------
# Write the generated module.
# ---------------------------------------------------------------------------
$directory = Split-Path -Parent $OutputPath
if (-not (Test-Path $directory)) { New-Item -ItemType Directory -Path $directory -Force | Out-Null }
Set-Content -LiteralPath $OutputPath -Value ($lines -join [char]10) -Encoding UTF8
Write-Output "Wrote $OutputPath ( $($exported.Count) cmdlets from $($registry.Count) resources)."

# ---------------------------------------------------------------------------
# Sync the manifest's FunctionsToExport so nothing falls out of sync.
# ---------------------------------------------------------------------------
$manifestPath = Join-Path (Split-Path -Parent $PSScriptRoot) 'ServiceM8.psd1'
if (Test-Path $manifestPath) {
    $engine = @(
        'Import-Sm8Config', 'Connect-Sm8Client', 'Get-Sm8Token',
        'Invoke-Sm8Request', 'Invoke-Sm8List', 'Invoke-Sm8Resource',
        'Get-Sm8ResourceRoot', 'Get-Sm8Registry'
    )
    $all = $engine + $exported
    $entryBlock = $all | ForEach-Object { "        '$_'" }
    $entryBlock = ($entryBlock -join ("," + [char]10))

    $pattern = '(?s)(FunctionsToExport\s*=\s*@\([^)]*\))'
    $newBlock = "FunctionsToExport    = @(" + [char]10 + $entryBlock + [char]10 + "    )"
    $manifest = [regex]::Replace((Get-Content -LiteralPath $manifestPath -Raw), $pattern, $newBlock)
    Set-Content -LiteralPath $manifestPath -Value $manifest -Encoding UTF8
    Write-Output "Synced FunctionsToExport in $manifestPath ( $($all.Count) exports)."
}
